# The core fixture sets up the Indicia database with a consistent set of 
# test data in the core tables.
# Id values in tables having sequences are never supplied so that, if a test
# adds a record to a table, the sequence will supply it the next valid id.
websites:
  -
    title: "Test website"
    description: "Website for unit testing"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    url: "http://www.indicia.org.uk"
    password: "password"

  
surveys:
  -
    title: "Test survey"
    description: "Survey for unit testing"
    website_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1


taxon_meanings: 
  # No support for INSERT INTO table DEFAULT VALUES.
  # Use high id values to avoid conflict with any values created by sequence
  # during testing
  -
    id: 10000
  -
    id: 10001

taxon_groups:
  -
    title: "Test taxon group"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1

  
taxon_lists:
  -
    title: "Test taxon list"
    description: "Taxon list for unit testing"
    website_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1

  
taxa:
  -
    taxon: "Test taxon"
    taxon_group_id: 1
    language_id: 2
    external_key: "TESTKEY"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    taxon: "Test taxon 2"
    taxon_group_id: 1
    language_id: 2
    external_key: "TESTKEY2"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1

  
taxa_taxon_lists:
  -
    taxon_list_id: 1
    taxon_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    taxon_meaning_id: 10000
    taxonomic_sort_order: 1
    preferred: "true"
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    taxon_list_id: 1
    taxon_id: 2
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    taxon_meaning_id: 10001
    taxonomic_sort_order: 1
    preferred: "true"
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1

 
cache_taxa_taxon_lists:
  -
    id: 1
    preferred: true
    taxon_list_id: 1
    taxon_list_title: "Test taxa taxon list"
    website_id: 1
    preferred_taxa_taxon_list_id: 1
    taxonomic_sort_order: 1
    taxon: "Test taxon"
    language_iso: "lat"
    language: "Latin"
    preferred_taxon: "Test taxon"
    preferred_language_iso: "lat"
    preferred_language: "Latin"
    external_key: "TESTKEY"
    taxon_meaning_id: 10000
    taxon_group_id: 1
    taxon_group: "Test taxon group"
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00
  -
    id: 2
    preferred: true
    taxon_list_id: 1
    taxon_list_title: "Test taxa taxon list 2"
    website_id: 1
    preferred_taxa_taxon_list_id: 2
    taxonomic_sort_order: 2
    taxon: "Test taxon 2"
    language_iso: "lat"
    language: "Latin"
    preferred_taxon: "Test taxon"
    preferred_language_iso: "lat"
    preferred_language: "Latin"
    external_key: "TESTKEY2"
    taxon_meaning_id: 10001
    taxon_group_id: 1
    taxon_group: "Test taxon group"
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00

cache_taxon_searchterms:
  -
    id: 1
    taxa_taxon_list_id: 1
    taxon_list_id: 1
    searchterm: "testtaxon"
    original: "Test taxon"
    taxon_group: "Test taxon group"
    taxon_meaning_id: 10000
    preferred_taxon: "Test taxon"
    default_common_name: "Test taxon"
    language_iso: "lat"
    name_type: "L"
    simplified: "t"
    taxon_group_id: 1
    preferred: "t"
    searchterm_length: 9
    preferred_taxa_taxon_list_id: 1
    external_key: "TESTKEY"
  -
    id: 2
    taxa_taxon_list_id: 1
    taxon_list_id: 1
    searchterm: "Test taxon"
    original: "Test taxon"
    taxon_group: "Test taxon group"
    taxon_meaning_id: 10000
    preferred_taxon: "Test taxon"
    default_common_name: "Test taxon"
    language_iso: "lat"
    name_type: "L"
    simplified: "f"
    taxon_group_id: 1
    preferred: "t"
    searchterm_length: 10
    preferred_taxa_taxon_list_id: 1
    external_key: "TESTKEY"
  -
    id: 3
    taxa_taxon_list_id: 2
    taxon_list_id: 1
    searchterm: "testtaxon2"
    original: "Test taxon 2"
    taxon_group: "Test taxon group"
    taxon_meaning_id: 10001
    preferred_taxon: "Test taxon 2"
    default_common_name: "Test taxon 2"
    language_iso: "lat"
    name_type: "L"
    simplified: "t"
    taxon_group_id: 1
    preferred: "t"
    searchterm_length: 10
    preferred_taxa_taxon_list_id: 1
    external_key: "TESTKEY2"
  -
    id: 4
    taxa_taxon_list_id: 2
    taxon_list_id: 1
    searchterm: "Test taxon 2"
    original: "Test taxon 2"
    taxon_group: "Test taxon group"
    taxon_meaning_id: 10001
    preferred_taxon: "Test taxon 2"
    default_common_name: "Test taxon 2"
    language_iso: "lat"
    name_type: "L"
    simplified: "f"
    taxon_group_id: 1
    preferred: "t"
    searchterm_length: 12
    preferred_taxa_taxon_list_id: 1
    external_key: "TESTKEY2"
  
meanings:
  # No support for INSERT INTO table DEFAULT VALUES.
  # Use high id values to avoid conflict with any values created by sequence
  # during testing
  -
    id: 10000
  -
    id: 10001
  -
    id: 10002
  -
    id: 10003
  -
    id: 10004


termlists:
  -
    title: "Test term list"
    description: "Term list list for unit testing"
    website_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    external_key: "TESTKEY"
  -
    title: "Location types"
    description: "Term list for location types"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    external_key: "indicia:location_types"
  -
    title: "Sample methods"
    description: "Term list for sample methods"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    external_key: "indicia:sample_methods"
  -
    title: "User identifier types"
    description: "Term list for user identifier types"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    external_key: "indicia:user_identifier_types"
    
  
terms:
  -
    term: "Test term"
    language_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    term: "Test location type"
    language_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    term: "Test sample method"
    language_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    term: "email"
    language_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  -
    term: "twitter"
    language_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
  
  
termlists_terms:
  -
    termlist_id: 1                          #Test term list
    term_id: 1                              #Test term
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    meaning_id: 10000
    preferred: "true"
    sort_order: 1
  -
    termlist_id: 2                          #Location types
    term_id: 2                              #Test location type
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    meaning_id: 10001
    preferred: "true"
    sort_order: 1
  -
    termlist_id: 3                          #Sample methods
    term_id: 3                              #Test sample method
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    meaning_id: 10002
    preferred: "true"
    sort_order: 1
  -
    termlist_id: 4                          #User identifier types
    term_id: 4                              #email
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    meaning_id: 10003
    preferred: "true"
    sort_order: 1
  -
    termlist_id: 4                          #User identifier types
    term_id: 5                              #twitter
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    meaning_id: 10004
    preferred: "true"
    sort_order: 2


cache_termlists_terms:
  -
    id: 1
    preferred: "true"
    termlist_id: 1
    termlist_title: "Test term list"
    website_id: 1
    preferred_termlists_term_id: 1
    sort_order: 1
    term: "Test term"
    language_iso: "eng"
    language: "English"
    preferred_term: "Test term"
    preferred_language_iso: "eng"
    preferred_language: "English"
    meaning_id: 10000
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00
  -
    id: 2
    preferred: "true"
    termlist_id: 2
    termlist_title: "Location types"
    website_id:
    preferred_termlists_term_id: 2
    sort_order: 1
    term: "Test location type"
    language_iso: "eng"
    language: "English"
    preferred_term: "Test location type"
    preferred_language_iso: "eng"
    preferred_language: "English"
    meaning_id: 10001
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00
  -
    id: 3
    preferred: "true"
    termlist_id: 3
    termlist_title: "Sample methods"
    website_id: 
    preferred_termlists_term_id: 3
    sort_order: 1
    term: "Test sample method"
    language_iso: "eng"
    language: "English"
    preferred_term: "Test term"
    preferred_language_iso: "eng"
    preferred_language: "English"
    meaning_id: 10002
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00
  -
    id: 4
    preferred: "true"
    termlist_id: 4
    termlist_title: "User identifier types"
    website_id: 
    preferred_termlists_term_id: 4
    sort_order: 1
    term: "email"
    language_iso: "eng"
    language: "English"
    preferred_term: "email"
    preferred_language_iso: "eng"
    preferred_language: "English"
    meaning_id: 10003
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00
  -
    id: 5
    preferred: "true"
    termlist_id: 4
    termlist_title: "User identifier types"
    website_id: 
    preferred_termlists_term_id: 5
    sort_order: 2
    term: "twitter"
    language_iso: "eng"
    language: "English"
    preferred_term: "email"
    preferred_language_iso: "eng"
    preferred_language: "English"
    meaning_id: 10004
    cache_created_on: 2016-07-22:16:00:00
    cache_updated_on: 2016-07-22:16:00:00


samples:
  -
    survey_id: 1
    date_start: "2016-07-22"
    date_end: "2016-07-22"
    date_type: "D"
    entered_sref: "SU01"
    entered_sref_system: "OSGB"
    comment: "Sample for unit testing"
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    recorder_names: "PHPUnit"
    record_status: "C"

map_squares:
  -
    geom: "010300002031BF0D0001000000050000004E9C282E3C320BC18FC3A8120A2F59412CCEAACFA94309C1E75E7B57062F5941A7DE4D3BB84209C11FD1A351893E5941BBB729FE3E320BC1D8E4B8118D3E59414E9C282E3C320BC18FC3A8120A2F5941"
    x: -214871
    y: 6609705
    size: 10000

occurrences:
  -
    sample_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    website_id: 1
    comment: "Occurrence for unit testing"
    taxa_taxon_list_id: 1
    record_status: "C"
    release_status: "R"
    confidential: "f"
  -
    sample_id: 1
    created_on: 2016-07-22:16:00:00
    created_by_id: 1
    updated_on: 2016-07-22:16:00:00
    updated_by_id: 1
    website_id: 1
    comment: "Confidential occurrence for unit testing"
    taxa_taxon_list_id: 1
    record_status: "C"
    release_status: "R"
    confidential: "t"
    
cache_occurrences_functional:
  -
    id: 1
    sample_id: 1
    website_id: 1
    survey_id: 1
    date_start: "2016-07-22"
    date_end: "2016-07-22"
    date_type: "D"
    created_on: 2016-07-22:16:00:00
    updated_on: 2016-07-22:16:00:00
    created_by_id: 1
    taxa_taxon_list_id: 1
    preferred_taxa_taxon_list_id: 1
    taxon_meaning_id: 10000
    taxa_taxon_list_external_key: "TESTKEY"
    taxon_group_id: 1
    record_status: "C"
    release_status: "R"
    zero_abundance: "f"
    confidential: "f"
    map_sq_1km_id: 1
    map_sq_2km_id: 1
    map_sq_10km_id: 1
  -
    id: 2
    sample_id: 1
    website_id: 1
    survey_id: 1
    date_start: "2016-07-22"
    date_end: "2016-07-22"
    date_type: "D"
    created_on: 2016-07-22:16:00:00
    updated_on: 2016-07-22:16:00:00
    created_by_id: 1
    taxa_taxon_list_id: 1
    preferred_taxa_taxon_list_id: 1
    taxon_meaning_id: 10000
    taxa_taxon_list_external_key: "TESTKEY"
    taxon_group_id: 1
    record_status: "C"
    release_status: "R"
    zero_abundance: "f"
    confidential: "t"
    map_sq_1km_id: 1
    map_sq_2km_id: 1
    map_sq_10km_id: 1

cache_occurrences_nonfunctional:
  -
    id: 1
  -
    id: 2

cache_samples_functional:
  -
    id: 1
    website_id: 1
    survey_id: 1
    date_start: "2016-07-22"
    date_end: "2016-07-22"
    date_type: "D"
    created_on: 2016-07-22:16:00:00
    updated_on: 2016-07-22:16:00:00
    created_by_id: 1
    record_status: "C"
    map_sq_1km_id: 1
    map_sq_2km_id: 1
    map_sq_10km_id: 1

cache_samples_nonfunctional:
  -
    id: 1
    website_title: "Test website"
    survey_title: "Test survey"
    public_entered_sref: "SU01"
    entered_sref_system: "OSGB"
    recorders: "PHPUnit"

locations:
  -
    name: "Test location"
    centroid_sref: "SU01"
    centroid_sref_system: "OSGB"
    location_type_id: "2"
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
    updated_on: "2016-07-22:16:00:00"
    updated_by_id: 1,
    public: "true"


location_attributes:
  -
    caption: "Test text"
    data_type: "T"
    public: "false"
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
    updated_on: "2016-07-22:16:00:00"
    updated_by_id: 1,
  -
    caption: "Test lookup"
    data_type: "L"
    termlist_id: 1,
    public: "false"
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
    updated_on: "2016-07-22:16:00:00"
    updated_by_id: 1,
  -
    caption: "Test integer"
    data_type: "I"
    termlist_id: 1,
    public: "false"
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
    updated_on: "2016-07-22:16:00:00"
    updated_by_id: 1,

        
location_attributes_websites:
  -
    website_id: 1                           #Test website
    location_attribute_id: 1,               #Test text
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
  -
    website_id: 1                           #Test website
    location_attribute_id: 2,               #Test lookup
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
  -
    website_id: 1                           #Test website
    location_attribute_id: 3,               #Test integer
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,


location_attribute_values:
  -
    location_id: 1,                         #Test location
    location_attribute_id: 2,               #Test lookup
    int_value: 1,                           #Test term
    created_on: "2016-07-22:16:00:00"
    created_by_id: 1,
    updated_on: "2016-07-22:16:00:00"
    updated_by_id: 1,
